name: Metrics
on:
  # Schedule updates every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Favorites anime and currently watching
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/metrics.plugin.anilist.recent.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: watching
          plugin_anilist_limit: 5
          plugin_anilist_user: jusuchin85
      
      - name: Last.fm  - Recently listed
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/metrics.plugin.lastfm.recent.svg
          token: NOT_NEEDED
          base: ""
          plugin_music_token: ${{ secrets.LASTFM_TOKEN }}
          plugin_music: yes
          plugin_music_provider: lastfm
          plugin_music_user: jusuchin85
          plugin_music_mode: recent
          plugin_music_limit: 10
