name: Waka Readme

on:
  schedule:
    # runs at every 12AM UTC
    - cron: '00 00 * * *'
  workflow_dispatch:
  push:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: "False"
          SHOW_PROJECTS: "False"
          SHOW_OS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_LOC_CHART: "False"
